dist: xenial

language: node_js
node_js:
  - "12.16.3"

# Unfortunately we cannot cache node_modules directory because
# the formio-editor libray would not be found, since it's taken
# from the dist (see optionalDependencies in package.json)
#
#cache:
#  directories:
#     - ./node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run formio-editor:build-prod   # this must run before test-headless to make it work
  - npm run test-headless
  - npm run build-prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/AngularFormioEditor
  on:
    branch: master