dist: xenial

language: node_js
node_js:
  - "12.16.3"

# Unfortunately we cannot cache node_modules directory because
# the formio-editor libray would not be found, since it's taken
# from the dist (see optionalDependencies in package.json)
#
#cache:
#  directories:
#     - ./node_modules

install:
  - npm install

script:
  - npm run build-all-prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/formio-editor-demo
  on:
    branch: master
