language: node_js
node_js:
  - "10.13"
addons:
  chrome: stable
services:
  - xvfb
before_script:
  - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - npm run build:lib build:app
  - sleep 3 # give Web server some time to bind to sockets, etc

before_install:
  - npm install -g typescript webdriver-manager ng-packagr @angular/cli@9.0.2
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install
  - webdriver-manager update
  - node node_modules/protractor/bin/webdriver-manager update
  - node_modules/protractor/bin/webdriver-manager update
